---
name: zizmor
"on":
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - .github/workflows/**.yaml
      - "**/action.yaml"
  push:
    branches:
      - main
    paths:
      - .github/workflows/**.yaml
      - "**/action.yaml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}
permissions:
  actions: read
  contents: read
  security-events: write # zizmor: ignore[excessive-permissions]
jobs:
  lint:
    name: Lint GitHub actions and workflows
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Lint Github actions and workflows
        run: |
          pipx run --quiet -- \
          zizmor --verbose --format=sarif --gh-hostname="${GITHUB_SERVER_URL#*://}" --persona=auditor . >zizmor.sarif
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Upload SARIF report to GitHub
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
        with:
          category: zizmor
          sarif_file: zizmor.sarif
